apiVersion: v1
kind: Service
metadata:
    name: go-demo
    namespace: demo
spec:
    selector:
        app: go-demo
    ports:
    - port: 8081
      targetPort: 8081
      nodePort: 31080
    type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: go-demo
    namespace: demo
spec:
    replicas: 1
    selector:
        matchLabels:
            app: go-demo
    template:
        metadata:
            labels:
                app: go-demo
        spec:
            containers:
            - name: go-hello-world
              image: goguo/go-web-hello-world:v0.1
              ports:
              - name: http
                containerPort: 8081
              resources:
                limits:
                    cpu: "0.3"
                    memory: 300M
                requests:
                    cpu: "0.1"
                    memory: 300M

